name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours; adjust as needed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation SVG
        uses: Platane/snk@master
        with:
          github_user_name: l0ne   # Replace with your GitHub username if different
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
